import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { runWorkspaceRuntimeGateway } from '../../src/runtime/workspace-runtime-gateway.js';

const workspace = await mkdtemp(join(tmpdir(), 'bioagent-agentserver-unavailable-'));
const result = await runWorkspaceRuntimeGateway({
  skillDomain: 'literature',
  prompt: 'Create a custom meta-analysis workflow that must be generated by AgentServer',
  workspacePath: workspace,
  availableSkills: ['force-agentserver-fallback'],
  scenarioPackageRef: { id: 'custom-literature-workflow', version: '0.1.0', source: 'workspace' },
  skillPlanRef: 'skill-plan/custom-literature-workflow@0.1.0',
  uiPlanRef: 'ui-plan/custom-literature-workflow@0.1.0',
});

assert.equal(result.artifacts.length, 0);
assert.equal(result.executionUnits.length, 1);

const unit = result.executionUnits[0] as Record<string, unknown>;
assert.equal(unit.status, 'repair-needed');
assert.match(String(unit.failureReason || result.message), /AgentServer|base URL/i);
assert.equal((unit.scenarioPackageRef as Record<string, unknown> | undefined)?.id, 'custom-literature-workflow');
assert.equal(unit.skillPlanRef, 'skill-plan/custom-literature-workflow@0.1.0');
assert.equal(unit.uiPlanRef, 'ui-plan/custom-literature-workflow@0.1.0');
assert.equal((unit.routeDecision as Record<string, unknown> | undefined)?.selectedRuntime, 'agentserver-generation');
assert.ok((unit.requiredInputs as string[] | undefined)?.includes('agentServerBaseUrl'));
assert.ok((unit.recoverActions as string[] | undefined)?.some((action) => /Start or configure AgentServer/.test(action)));
assert.match(String(unit.nextStep), /Start AgentServer|local skill/);

console.log('[ok] AgentServer unavailable diagnostics include route, package refs, required inputs, and recovery actions');
