import type { UIComponentElement } from './elementTypes';

export const uiComponentElements: UIComponentElement[] = [
  {
    id: 'component.paper-card-list',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Paper cards',
    description: 'Render PubMed/Semantic Scholar style paper-list artifacts as evidence cards.',
    source: 'built-in',
    componentId: 'paper-card-list',
    acceptsArtifactTypes: ['paper-list'],
    requiredFields: ['papers'],
    viewParams: ['filter', 'sort', 'limit', 'colorBy'],
    interactionEvents: ['select-paper', 'select-target'],
    roleDefaults: ['experimental-biologist', 'pi'],
    fallback: 'data-table',
  },
  {
    id: 'component.molecule-viewer',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Molecule viewer',
    description: 'Render structure-summary artifacts with 3Dmol-based structure visualization.',
    source: 'built-in',
    componentId: 'molecule-viewer',
    acceptsArtifactTypes: ['structure-summary'],
    requiredFields: ['dataRef'],
    viewParams: ['colorBy', 'highlightSelection', 'syncViewport'],
    interactionEvents: ['highlight-residue', 'select-chain'],
    roleDefaults: ['experimental-biologist', 'bioinformatician'],
    fallback: 'unknown-artifact-inspector',
  },
  {
    id: 'component.volcano-plot',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Volcano plot',
    description: 'Render differential-expression points as a volcano plot.',
    source: 'built-in',
    componentId: 'volcano-plot',
    acceptsArtifactTypes: ['omics-differential-expression'],
    requiredFields: ['points'],
    viewParams: ['colorBy', 'filter', 'x', 'y', 'label'],
    interactionEvents: ['select-gene'],
    roleDefaults: ['bioinformatician', 'pi'],
    fallback: 'data-table',
  },
  {
    id: 'component.heatmap-viewer',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Heatmap viewer',
    description: 'Render matrix payloads from omics artifacts.',
    source: 'built-in',
    componentId: 'heatmap-viewer',
    acceptsArtifactTypes: ['omics-differential-expression'],
    requiredFields: ['heatmap'],
    viewParams: ['colorBy', 'splitBy', 'facetBy'],
    interactionEvents: ['select-gene-set'],
    roleDefaults: ['bioinformatician'],
    fallback: 'data-table',
  },
  {
    id: 'component.umap-viewer',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'UMAP viewer',
    description: 'Render embedding coordinates from omics artifacts.',
    source: 'built-in',
    componentId: 'umap-viewer',
    acceptsArtifactTypes: ['omics-differential-expression'],
    requiredFields: ['umap'],
    viewParams: ['colorBy', 'splitBy', 'highlightSelection'],
    interactionEvents: ['select-cluster'],
    roleDefaults: ['bioinformatician', 'experimental-biologist'],
    fallback: 'data-table',
  },
  {
    id: 'component.network-graph',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Network graph',
    description: 'Render knowledge graph nodes and edges.',
    source: 'built-in',
    componentId: 'network-graph',
    acceptsArtifactTypes: ['knowledge-graph'],
    requiredFields: ['nodes', 'edges'],
    viewParams: ['colorBy', 'filter', 'highlightSelection'],
    interactionEvents: ['select-node', 'select-edge'],
    roleDefaults: ['experimental-biologist', 'pi'],
    fallback: 'data-table',
  },
  {
    id: 'component.evidence-matrix',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Evidence matrix',
    description: 'Render session claims and evidence levels.',
    source: 'built-in',
    componentId: 'evidence-matrix',
    acceptsArtifactTypes: ['paper-list', 'structure-summary', 'knowledge-graph', 'omics-differential-expression'],
    requiredFields: [],
    viewParams: ['filter', 'sort', 'limit'],
    interactionEvents: ['select-claim'],
    roleDefaults: ['experimental-biologist', 'pi', 'clinical'],
    fallback: 'unknown-artifact-inspector',
  },
  {
    id: 'component.execution-unit-table',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Execution units',
    description: 'Render reproducible execution units, logs, code refs, and statuses.',
    source: 'built-in',
    componentId: 'execution-unit-table',
    acceptsArtifactTypes: ['paper-list', 'structure-summary', 'knowledge-graph', 'omics-differential-expression', 'sequence-alignment', 'inspection-summary'],
    requiredFields: [],
    viewParams: ['filter', 'sort', 'limit'],
    interactionEvents: ['open-code-ref', 'open-log-ref'],
    roleDefaults: ['bioinformatician', 'pi'],
    fallback: 'unknown-artifact-inspector',
  },
  {
    id: 'component.notebook-timeline',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Notebook timeline',
    description: 'Render the structured research notebook timeline.',
    source: 'built-in',
    componentId: 'notebook-timeline',
    acceptsArtifactTypes: ['paper-list', 'structure-summary', 'knowledge-graph', 'omics-differential-expression'],
    requiredFields: [],
    viewParams: ['filter', 'sort', 'limit'],
    interactionEvents: ['select-timeline-event'],
    roleDefaults: ['experimental-biologist', 'pi'],
    fallback: 'unknown-artifact-inspector',
  },
  {
    id: 'component.data-table',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Data table',
    description: 'Generic tabular artifact renderer.',
    source: 'built-in',
    componentId: 'data-table',
    acceptsArtifactTypes: ['paper-list', 'structure-summary', 'knowledge-graph', 'omics-differential-expression', 'sequence-alignment', 'inspection-summary'],
    requiredFields: [],
    viewParams: ['filter', 'sort', 'limit', 'group'],
    interactionEvents: ['select-row'],
    roleDefaults: ['bioinformatician', 'pi'],
    fallback: 'unknown-artifact-inspector',
  },
  {
    id: 'component.unknown-artifact-inspector',
    kind: 'ui-component',
    version: '1.0.0',
    label: 'Unknown artifact inspector',
    description: 'Safe fallback for JSON, table, file, and log previews.',
    source: 'built-in',
    componentId: 'unknown-artifact-inspector',
    acceptsArtifactTypes: ['*'],
    requiredFields: [],
    viewParams: ['filter', 'sort', 'limit'],
    interactionEvents: ['open-ref'],
    roleDefaults: ['bioinformatician', 'pi'],
    fallback: 'unknown-artifact-inspector',
  },
];

